Forcing images visibility to be public.

diff --git a/.github/workflows/ubuntu-baseimages.yml b/.github/workflows/ubuntu-baseimages.yml
--- a/.github/workflows/ubuntu-baseimages.yml
+++ b/.github/workflows/ubuntu-baseimages.yml
@@ -201,22 +201,29 @@ jobs:
           cache-from: type=gha,scope=${{ github.workflow }}-${{ matrix.os_version }}
           cache-to: type=gha,mode=max,scope=${{ github.workflow }}-${{ matrix.os_version }}
 
-      # Determines the type of the repository owner (User or Organization)
+  make-packages-public:
+    name: Make Packages Public
+    runs-on: ubuntu-latest
+    needs: check-and-build
+    permissions:
+      packages: write
+    steps:
+      - name: 'Convert repository owner to lowercase'
+        id: lowercase_owner
+        run: echo "owner=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT
+
       - name: Get repository owner type
         id: owner_type
-        if: ${{ steps.check_changes.outputs.changed == 'true' && success() }}
         run: |
           OWNER_TYPE=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/users/${{ github.repository_owner }}" | jq -r .type)
           echo "type=${OWNER_TYPE}" >> $GITHUB_OUTPUT
 
-      # Makes the container packages public after they are pushed
       - name: Make packages public
-        if: ${{ steps.check_changes.outputs.changed == 'true' && success() }}
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
           LOWERCASE_OWNER="${{ steps.lowercase_owner.outputs.owner }}"
-          PACKAGE_NAMES="ubuntu ubuntu-${{ matrix.os_name }} ubuntu-${{ matrix.os_version }}"
+          PACKAGE_NAMES="ubuntu ubuntu-noble ubuntu-24.04 ubuntu-jammy ubuntu-22.04 ubuntu-focal ubuntu-20.04 ubuntu-bionic ubuntu-18.04 ubuntu-xenial ubuntu-16.04 ubuntu-trusty ubuntu-14.04"
 
           if [ "${{ steps.owner_type.outputs.type }}" == "Organization" ]; then
             API_BASE_URL="https://api.github.com/orgs/$LOWERCASE_OWNER/packages/container"
@@ -230,7 +237,7 @@ jobs:
               -H "Authorization: token $GITHUB_TOKEN" \
               -H "Accept: application/vnd.github.v3+json" \
               "$API_BASE_URL/$PACKAGE_NAME" \
-              -d '{"visibility":"public"}'
+              -d '{"visibility":"public"}' || echo "Could not make package $PACKAGE_NAME public. It may not exist or is already public."
           done
             
   # Job to update the README file
